# Generated by Django 4.2 on 2023-12-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='books',
            field=models.ManyToManyField(related_name='users', to='book.book', verbose_name='books'),
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_book',
            field=models.ManyToManyField(related_name='favorite_users', to='book.book', verbose_name='favorite-book'),
        ),
    ]
