# Generated by Django 4.2 on 2023-12-25 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publisher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='permissions',
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'verbose_name': 'publisher', 'verbose_name_plural': 'publishers'},
        ),
        migrations.AlterModelOptions(
            name='publisheruser',
            options={'verbose_name': 'publisher-user', 'verbose_name_plural': 'publisher-users'},
        ),
        migrations.RemoveField(
            model_name='publisheruser',
            name='role',
        ),
        migrations.AddField(
            model_name='publisher',
            name='admin',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='publisher_admin', to='publisher.publisheruser', verbose_name='admin'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='publisheruser',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publisher.publisher', verbose_name='publisher'),
        ),
        migrations.AlterField(
            model_name='publisheruser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
